/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_javacallc_JNI */

#ifndef _Included_com_example_javacallc_JNI
#define _Included_com_example_javacallc_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_javacallc_JNI
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_javacallc_JNI_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_javacallc_JNI
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_javacallc_JNI_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_javacallc_JNI
 * Method:    mult
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_javacallc_JNI_mult
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
